export const APP_STRINGS = {
  appName: "Operix",
  appDescription: "Super Admin Financial & Operations Dashboard",
  welcomePrefix: "Welcome Back,",
  actions: {
    addNewWallet: "Add New Wallet",
    send: "Send",
    receive: "Receive",
    viewAll: "View All",
    monthly: "Monthly",
    annually: "Annually",
    searchPlaceholder: "Search anything...",
    notifications: "Notifications",
    openSettings: "Open Settings",
    expand: "Expand Details",
    logout: "Log out",
  },
  headers: {
    paymentGoal: "Payment Goal",
    paymentGoalSubtitle: "Total amount goal",
    engagementRate: "Engagement Rate",
    totalBalance: "Total Balance",
    weeklyRevenue: "Weekly Revenue",
    amountOfCredit: "Amount of credit",
    paymentHistory: "Payment History",
    paymentHistorySubtitle: "Recent payment history",
    mandatoryPayments: "Mandatory Payments",
    mandatoryPaymentsSubtitle: "Upcoming payments",
  },
  tableColumns: {
    name: "NAME",
    date: "DATE",
    time: "TIME",
    status: "STATUS",
    amount: "AMOUNT",
  },
  cardDetails: {
    creditCard: "Credit Card",
    visa: "VISA",
    mastercard: "MASTERCARD",
    expPrefix: "Exp",
  },
  ariaLabels: {
    userProfile: "User Profile Menu",
    notifications: "View notifications",
    search: "Search dashboard",
    dateRangeSelector: "Select date range filter",
    addNewWallet: "Add new wallet",
    cardOptions: "Credit card options",
    engagementFilter: "Filter engagement rate by time period",
    sendMoney: "Send money",
    receiveMoney: "Receive money",
    viewPaymentHistoryOptions: "Payment history filter options",
    viewMandatoryPayments: "View upcoming mandatory payments",
    addMandatoryPayee: "Add new mandatory payee",
    mainNavigation: "Main navigation sidebar",
    topNavigation: "Top navigation tabs",
  },
} as const;
