/**
 * Operix Authentication & Registration String Constants
 * Centralized user-facing copy adhering to the no-hardcoded-strings rule.
 */

export const AUTH_STRINGS = {
  brand: {
    name: "Operix",
    subName: "Operations",
    tagline: "Pharmaceutical Operations & Governance",
    copyright: "© 2026 Operix • Pharmaceutical Workload & Operations Management Platform.",
  },
  signIn: {
    title: "Sign In to Portal",
    subtitle:
      "Enter your enterprise credentials to access your personalized pharmaceutical workspace.",
    emailLabel: "Work Email",
    emailPlaceholder: "name@operix.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    forgotPasswordNotice: "For password recovery, please contact your Operix IT Administrator.",
    submitBtn: "Sign In to Portal",
    submittingBtn: "Authenticating...",
    noAccountPrompt: "Don't have an account?",
    requestAccessLink: "Request Access / Sign Up",
    backToOverview: "← Back to Portal Overview",
  },
  signUp: {
    title: "Request Portal Access",
    subtitle:
      "Submit your details to request an Operix enterprise account. Your request will be reviewed by the Super Admin.",
    nameLabel: "Full Name",
    namePlaceholder: "e.g. Dr. Sarah Rahman",
    emailLabel: "Work Email",
    emailPlaceholder: "sarah.rahman@operix.com",
    designationLabel: "Requested Designation / Title",
    designationPlaceholder: "e.g. Quality Assurance Specialist",
    employeeIdLabel: "Employee ID (Optional)",
    employeeIdPlaceholder: "e.g. EMP-9042",
    submitBtn: "Submit Access Request",
    submittingBtn: "Submitting Request...",
    alreadyHaveAccount: "Already have an account?",
    signInLink: "Sign In",
    successTitle: "Access Request Submitted",
    successMessage: "Your registration request has been submitted to the Super Admin for review.",
    successExplanation:
      "Once accepted, you will receive an official email containing a secure link to set up your password and choose your access credentials.",
    backToHome: "Return to Sign In",
    errors: {
      nameRequired: "Full Name is required.",
      emailRequired: "Work Email is required.",
      emailInvalid: "Please enter a valid work email address.",
      genericFailure: "Failed to submit request. Please try again or contact IT support.",
    },
  },
  setupPassword: {
    title: "Set Up Your Password",
    subtitle: "Create a secure password to activate your Operix pharmaceutical workspace account.",
    newPasswordLabel: "New Password",
    newPasswordPlaceholder: "Enter your new password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Re-enter your new password",
    submitBtn: "Activate Account & Set Password",
    submittingBtn: "Setting Password...",
    successTitle: "Password Set Successfully!",
    successMessage: "Your password has been configured and your account is now fully active.",
    proceedToSignIn: "Proceed to Sign In",
    invalidTokenTitle: "Invalid or Expired Link",
    invalidTokenMessage:
      "This password setup link is invalid or has expired. Please contact your administrator or request a new invitation.",
    rules: {
      minLength: "At least 8 characters long",
      hasUppercase: "At least one uppercase letter (A-Z)",
      hasLowercase: "At least one lowercase letter (a-z)",
      hasNumber: "At least one numeric digit (0-9)",
      hasSpecial: "At least one special character (!@#$%^&*)",
      passwordsMatch: "Passwords match",
    },
    errors: {
      tokenMissing: "Missing password setup token in the URL.",
      passwordMismatch: "Passwords do not match.",
      policyUnmet: "Please meet all enterprise password security requirements.",
      genericFailure: "Failed to set password. Please check your setup link or try again.",
    },
  },
  adminApproval: {
    pendingTab: "Pending Registrations",
    activeTab: "Active Admins",
    reviewAction: "Review & Decide Role",
    rejectAction: "Reject",
    dialogTitle: "Review Registration Request",
    dialogDescription:
      "Review applicant details, assign their organizational role, and approve their account.",
    roleSectionTitle: "Assign Organization Role",
    roleAdminLabel: "Admin / Team Lead",
    roleAdminDesc: "Can manage members, assign tasks, and submit operational reports.",
    roleMemberLabel: "Member / Staff",
    roleMemberDesc: "Can execute assigned tasks, submit work, and update task progress.",
    employeeIdLabel: "Employee ID",
    designationLabel: "Designation",
    teamAssignmentLabel: "Assign to Team (for Members)",
    noTeamOption: "No Team Assigned",
    approveBtn: "Approve & Send Password Setup Email",
    approvingBtn: "Approving & Provisioning...",
    rejectDialogTitle: "Reject Registration Request",
    rejectReasonLabel: "Rejection Reason (Optional)",
    rejectConfirmBtn: "Confirm Rejection",
    rejectionSuccess: "Registration request rejected.",
    approvalSuccess: "Account approved! Password setup email sent to the user.",
    noPendingRequestsTitle: "No Pending Registrations",
    noPendingRequestsMessage: "All registration requests have been reviewed and processed.",
  },
} as const;
