export const APP_STRINGS = {
  appName: "Operix",
  appDescription: "Super Admin Financial & Operations Dashboard",
  dashboardTitles: {
    superAdmin: "Operix - Super Admin Dashboard",
    admin: "Operix - Admin Dashboard",
    member: "Operix - Member Dashboard",
    default: "Operix - Dashboard",
  },
  welcomePrefix: "Welcome Back,",
  actions: {
    addNewWallet: "Add New Wallet",
    exportReport: "Export Report",
    last6Months: "Last 6 Months",
    send: "Send",
    receive: "Receive",
    viewAll: "View All",
    monthly: "Monthly",
    annually: "Annually",
    searchPlaceholder: "Search anything...",
    notifications: "Notifications",
    openSettings: "Open Settings",
    expand: "Expand Details",
    logout: "Log out",
    download: "Download",
    moreOptions: "More Options",
  },
  headers: {
    dashboard: "Dashboard",
    reports: "Reports",
    paymentGoal: "Payment Goal",
    paymentGoalSubtitle: "Total amount goal",
    engagementRate: "Engagement Rate",
    totalBalance: "Total Balance",
    weeklyRevenue: "Weekly Revenue",
    amountOfCredit: "Amount of credit",
    paymentHistory: "Payment History",
    paymentHistorySubtitle: "Recent payment history",
    mandatoryPayments: "Mandatory Payments",
    mandatoryPaymentsSubtitle: "Upcoming payments",
    revenueVsExpenses: "Revenue vs Expenses",
    recentReports: "Recent Reports",
  },
  tableColumns: {
    name: "NAME",
    date: "DATE",
    time: "TIME",
    status: "STATUS",
    amount: "AMOUNT",
    reportName: "REPORT NAME",
    type: "TYPE",
    generatedDate: "GENERATED DATE",
    actions: "ACTIONS",
  },
  cardDetails: {
    creditCard: "Credit Card",
    visa: "VISA",
    mastercard: "MASTERCARD",
    expPrefix: "Exp",
  },
  chartLegends: {
    revenue: "Revenue",
    expenses: "Expenses",
  },
  ariaLabels: {
    userProfile: "User Profile Menu",
    notifications: "View notifications",
    search: "Search dashboard",
    dateRangeSelector: "Select date range filter",
    addNewWallet: "Add new wallet",
    exportReport: "Export report file",
    cardOptions: "Credit card options",
    engagementFilter: "Filter engagement rate by time period",
    sendMoney: "Send money",
    receiveMoney: "Receive money",
    viewPaymentHistoryOptions: "Payment history filter options",
    viewMandatoryPayments: "View upcoming mandatory payments",
    addMandatoryPayee: "Add new mandatory payee",
    mainNavigation: "Main navigation sidebar",
    topNavigation: "Top navigation tabs",
    downloadReport: "Download report document",
    reportOptions: "Report item options",
  },
} as const;
