/**
 * Centralized string constants for Dashboard Analytics and KPI cards.
 * Avoids hardcoded strings in components and adheres to design system rules.
 */
export const DASHBOARD_STRINGS = {
  hero: {
    eyebrow: "Operational snapshot",
    heading: "Dashboard",
    welcomePrefix: "Welcome back,",
    welcomeSuffix: ". Here is the dynamic role-tailored snapshot for your account.",
    asOfLabel: "Overview as of",
    datePickerPlaceholder: "Loading...",
    datePickerAria: "Select overview snapshot date",
  },
  roles: {
    superAdmin: "Super Admin / Chief",
    admin: "Admin",
    member: "Member / Staff",
  },
  sections: {
    overviewTitle: "Overview",
    overviewDesc: "Executive operational overview and performance trends.",
    workloadTitle: "Workload",
    workloadDesc: "Current workload distribution and team capacity.",
    directDataStreamNotice:
      "Direct Operational Data Stream — Exposed directly to eliminate manual spreadsheet collection & calculations.",
    emptyOverviewTitle: "No Overview data",
    emptyOverviewMessage: "No Dashboard Overview was returned.",
    emptyWorkloadTitle: "No Workload data",
    emptyWorkloadMessage: "No Dashboard Workload was returned.",
  },
  cards: {
    activeWorkload: "Active Workload",
    operationalScope: "Operational Scope",
    managedScope: "Managed Scope",
    completionRate: "Completion Rate",
    managementReports: "Management Reports",
    mySubmittedReports: "My Submitted Reports",
    myActiveTasks: "My Active Tasks",
    taskQuality: "Task Quality",
    myPerformance: "My Performance",
    unreadAlerts: "Unread Alerts",
  },
  badges: {
    quality: "Quality",
    efficiency: "Efficiency",
    reports: "Reports",
    score: "Score",
    inbox: "Inbox",
    awaitingData: "Awaiting Data",
    totalPrefix: "Total:",
    pendingPrefix: "Pending:",
  },
  metrics: {
    totalTasks: "Total Tasks",
    activeTasks: "Active Tasks",
    completedTasks: "Completed Tasks",
    overdueTasks: "Overdue Tasks",
    cancelledTasks: "Cancelled Tasks",
    reviewQueue: "Review Queue",
    scopedTeams: "Scoped Teams",
    totalTeams: "Total Teams",
    totalAdmins: "Total Admins",
    dueSoon: "Due Soon",
    revisionRequired: "Revision Required",
    onTimeRate: "On Time Rate",
    averageCompletion: "Average Completion",
    reportsNeedingRevision: "Reports Needing Revision",
    revisionRequiredTasks: "Revision Required Tasks",
    draftReports: "Draft Reports",
  },
  charts: {
    activeTasksByPriority: "Active Tasks by Priority",
    activePrioritySubtitle: "Urgency distribution across active workload",
    managementReportsBreakdown: "Management Reports Breakdown",
    managementReportsSubtitle: "Approval funnel & report status pipeline",
    taskStatusDistribution: "Task Status Distribution",
    taskStatusSubtitle: "Volume proportion by status",
    completionTrends: "Completion Trends",
    completionTrendsSubtitle: "Task completion velocity across recent period",
    totalItems: "TOTAL ITEMS",
    tasksCompletedWindow: "tasks completed in selected window",
    noTrendBucketsTitle: "No trend buckets",
    noTrendBucketsMessage: "No completion trend buckets returned.",
  },
  activities: {
    recentActivityTitle: "Recent Activity",
    recentActivitySubtitle: "Real-time updates across the workspace",
    viewAllActivity: "View all Activity",
    noRecentActivityTitle: "No recent activity",
    noRecentActivityMessage: "No activity records returned.",
  },
  notifications: {
    recentNotificationsTitle: "Recent Notifications",
    recentNotificationsSubtitle: "Workspace alerts and direct assignments",
    viewAllNotifications: "View all Notifications",
    noRecentNotificationsTitle: "No recent notifications",
    noRecentNotificationsMessage: "No notification records returned.",
  },
  units: {
    team: "Team",
    teams: "Teams",
    member: "Member",
    members: "Members",
    revision: "Revision",
    revisions: "Revisions",
    task: "task",
    tasks: "tasks",
    min: "min",
  },
} as const;
