export const TASK_DETAILS_STRINGS = {
  breadcrumbs: {
    dashboard: "Dashboard",
    tasks: "Tasks",
  },
  navigation: {
    backToTasks: "Back to Tasks",
  },
  eyebrow: "Task Details",
  referenceCode: {
    label: "REF",
    copyAria: "Copy reference code",
    copyTitle: "Copy reference code",
    copied: "Copied!",
  },
  badges: {
    overdue: "Overdue",
    onTrack: "On Track",
    recurring: "Recurring",
    selfClaim: "Self-Claim Enabled",
  },
  actions: {
    assignTask: "Assign Task",
    startTask: "Start Task",
    claimTask: "Claim Task",
    completeTask: "Complete Task",
    claiming: "Claiming...",
    completing: "Completing...",
  },
  stepper: {
    title: "Workflow Progress",
    stages: {
      pending: "Created",
      assigned: "Assigned",
      inProgress: "In Progress",
      underReview: "Review",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    subtitles: {
      pending: "Awaiting assignment",
      assigned: "Assigned to member",
      inProgress: "Work underway",
      underReview: "Submission review",
      completed: "Verified & closed",
      cancelled: "Task cancelled",
      revisionRequired: "Revision requested",
    },
  },
  sections: {
    overview: "Task Overview",
    description: "Description",
    remarks: "Instructions & Remarks",
    lifecycle: "Lifecycle & Timeline",
    ownership: "Ownership & Context",
    workspace: "Workspace",
  },
  tabs: {
    submissions: "Submissions",
    attachments: "Attachments",
    history: "Activity History",
  },
  metadata: {
    status: "Status",
    priority: "Priority",
    scope: "Task Scope",
    scopeGlobal: "Global (Organization-wide)",
    scopeTeam: "Team",
    distribution: "Distribution",
    distributionSent: "Sent to organization",
    distributionPending: "Scheduled broadcast",
    distributionCancelled: "Distribution cancelled",
    overdue: "Overdue",
    team: "Team Reference",
    category: "Category Reference",
    createdBy: "Created By",
    assignedTo: "Assigned To",
    unassigned: "Unassigned",
    dueDate: "Due Date",
    startedAt: "Started",
    completedAt: "Completed",
    cancelledAt: "Cancelled",
    createdAt: "Created",
    updatedAt: "Updated",
    notApplicable: "—",
    none: "None",
    noDescription: "No description provided for this task.",
    noRemarks: "No special remarks or instructions provided.",
    reminder: "Deadline Reminder",
    reminderScheduled: "Reminder scheduled",
    recurrence: "Recurrence Schedule",
    recurrenceWeekly: "Weekly",
    recurrenceMonthly: "Monthly",
    nextOccurrence: "Next Occurrence",
    selfClaim: "Self-Claim Policy",
    selfClaimEnabled: "Allowed for Members",
    selfClaimDisabled: "Disabled (Admin assignment only)",
    completionMode: "Completion Mode",
    completionModeDirect: "Direct Completion",
    completionModeReview: "Review Required",
    completionNote: "Completion Note",
  },
  directCompletionDialog: {
    title: "Complete Task",
    description: "Mark this task as completed directly without requiring submission review.",
    noteLabel: "Completion remarks (optional)",
    notePlaceholder: "Add any closing remarks or summary of completed work...",
    submitButton: "Mark Completed",
    cancelButton: "Cancel",
  },
  distributionManagement: {
    reschedule: "Reschedule",
    cancelDistribution: "Cancel Distribution",
    confirmCancelTitle: "Cancel Distribution?",
    confirmCancelMessage:
      "This will permanently cancel the scheduled broadcast. Members will not be notified about this global task.",
    confirmCancelAction: "Yes, Cancel Distribution",
    confirmCancelDismiss: "Keep Scheduled",
    rescheduleSuccess: "Distribution rescheduled successfully.",
    cancelSuccess: "Distribution cancelled.",
    scheduledAtLabel: "Scheduled for",
    sentAtLabel: "Distributed on",
    leadMinutesLabel: "Lead time",
  },
  loading: "Loading Task...",
} as const;

export const TASK_TABLE_STRINGS = {
  columns: {
    reference: "Reference",
    title: "Title",
    priority: "Priority",
    status: "Status",
    assignee: "Assigned To",
    createdBy: "Created By",
    team: "Team",
    due: "Due",
    overdue: "Overdue",
    created: "Created",
    actions: "Actions",
  },
  labels: {
    teamPrefix: "Team:",
    duePrefix: "Due:",
    createdPrefix: "Created:",
    assigneePrefix: "Assigned To:",
    creatorPrefix: "Created By:",
  },
  badges: {
    overdue: "Overdue",
    notOverdue: "No",
    unassigned: "Unassigned",
    globalScope: "Global",
    recurring: "Recurring",
  },
  actions: {
    view: "View",
    assign: "Assign",
    claim: "Claim",
    start: "Start",
  },
} as const;

export const TASK_ROLE_LABELS: Record<string, string> = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  MEMBER: "Member",
};

export const TASK_CREATE_STRINGS = {
  eyebrow: "Operations",
  title: "Create Task",
  description: "Define a new operational task, assign it to a team, and schedule execution.",
  breadcrumbs: {
    dashboard: "Dashboard",
    tasks: "Tasks",
    current: "New Task",
  },
  navigation: {
    backToTasks: "Back to Tasks",
  },
  sections: {
    generalInfo: "Task Information",
    generalInfoSubtitle: "Define the core requirements, instructions, and internal remarks.",
    configuration: "Assignment & Schedule",
    configurationSubtitle: "Select the responsible team and specify task deadline.",
    guidelines: "Task Lifecycle & Governance",
  },
  fields: {
    titleLabel: "Task Title",
    titleRequired: "*",
    titlePlaceholder: "e.g., Prepare quarterly compliance report",
    titleHelper: "A concise, descriptive summary of the required work.",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Detailed task instructions, deliverables, and acceptance criteria...",
    descriptionHelper: "Provide comprehensive background and execution context.",
    remarksLabel: "Internal Remarks",
    remarksPlaceholder: "Optional internal notes or coordination guidelines...",
    remarksHelper: "Visible to team leads and designated assignees.",
    priorityLabel: "Priority Level",
    priorityHelper: "Select operational urgency level for this task.",
    dueAtLabel: "Due Date & Time",
    dueAtHelper: "Target completion timestamp (optional).",
    dueAtPlaceholder: "Select deadline date & time...",
    dueAtAriaLabel: "Select due date and time",
    scopeLabel: "Task Scope",
    scopeTeam: "Team Task",
    scopeTeamDescription: "Assigned to and executed by members of a specific team.",
    scopeGlobal: "Global Task",
    scopeGlobalDescription: "Organization-wide task without a team, completed directly.",
    teamLabel: "Target Team",
    teamRequired: "*",
    teamHelper: "Choose which team will be responsible for executing this task.",
    teamNotRequiredForGlobal: "Global tasks apply across the entire organization and do not require a team.",
    selectedTeamPrefix: "Selected:",
    clearTeam: "Clear",
    distributionLabel: "In-App Member Notification",
    distributionNotifyAll: "Broadcast notification to all members",
    distributionNotifyAllHelper: "Sends an immediate in-app broadcast announcement to every active member and admin.",
  },
  distribution: {
    scheduleLabel: "Distribution Schedule",
    modeImmediate: "Immediate",
    modeScheduled: "Scheduled",
    modeLeadTime: "Lead Time",
    modeImmediateDescription: "Broadcast to all members as soon as the task is created.",
    modeScheduledDescription: "Schedule the broadcast for a specific date and time.",
    modeLeadTimeDescription: "Distribute automatically before the task deadline.",
    scheduledAtLabel: "Distribution Date & Time",
    scheduledAtPlaceholder: "Select distribution date & time...",
    scheduledAtAriaLabel: "Select distribution schedule date and time",
    scheduledAtHelper: "Members will receive the notification at this exact time.",
    leadTimeLabel: "Lead Time Before Deadline",
    leadTimeHelper: "The broadcast will fire this long before the task's due date.",
    leadTimeRequiresDueDate: "A due date is required to use lead-time distribution.",
    presets: {
      "1440": "24 hours before deadline",
      "2880": "48 hours before deadline",
      "4320": "72 hours before deadline",
      "10080": "1 week before deadline",
    } as Record<string, string>,
    infoCallout: "Clock-wise distributions are processed automatically by the system's hourly automation engine.",
  },
  selfClaim: {
    sectionLabel: "Self-Claim Policy",
    enableLabel: "Allow eligible Members to self-claim this task",
    enableHelper:
      "When enabled, active members can directly pick up and assign this task to themselves from the task list.",
    disabledForRecurring: "Self-claim cannot be combined with recurring task schedules.",
  },
  recurrence: {
    sectionLabel: "Recurrence Schedule",
    modeNone: "One-Time Task",
    modeWeekly: "Weekly",
    modeMonthly: "Monthly",
    modeNoneDescription: "Standard one-time task execution.",
    modeWeeklyDescription: "Repeats on the same day every week.",
    modeMonthlyDescription: "Repeats automatically every month (e.g. 5th of each month).",
    infoCallout:
      "Recurring tasks automatically generate new occurrences and broadcast scheduled clock-wise reminders.",
  },
  reminder: {
    sectionLabel: "Deadline Reminder",
    enableLabel: "Send automated reminder before deadline",
    enableHelper: "The system will send an in-app notification and email when the reminder fires.",
    leadTimeLabel: "Reminder Lead Time",
    leadTimeHelper: "How far in advance of the deadline to send the reminder.",
    requiresDueDate: "Set a due date above to enable deadline reminders.",
    presets: {
      "30": "30 minutes before",
      "60": "1 hour before",
      "240": "4 hours before",
      "1440": "24 hours before",
      "2880": "48 hours before",
    } as Record<string, string>,
  },
  dateTimePicker: {
    dialogAriaLabel: "Due date and time picker",
    presetsTitle: "Quick Schedule",
    presets: {
      todayEod: "Today 5 PM",
      tomorrowMorning: "Tomorrow 9 AM",
      tomorrowEod: "Tomorrow 5 PM",
      nextWeek: "Next Week",
    },
    timeTitle: "Time",
    hoursLabel: "Hour",
    minutesLabel: "Minute",
    periodLabel: "Period",
    quickTimes: {
      morning: "9:00 AM",
      noon: "12:00 PM",
      eod: "5:00 PM",
      night: "11:59 PM",
    },
    actions: {
      clear: "Clear",
      now: "Now",
      apply: "Apply",
      today: "Today",
      prevMonth: "Previous month",
      nextMonth: "Next month",
    },
  },
  priorities: {
    LOW: { label: "Low", description: "Standard backlog item" },
    MEDIUM: { label: "Medium", description: "Normal operational priority" },
    HIGH: { label: "High", description: "Time-sensitive deliverable" },
    URGENT: { label: "Urgent", description: "Critical blocker requiring immediate action" },
  },
  guidelines: [
    {
      title: "Pending by default",
      description: "Tasks are created in PENDING status until an admin assigns them.",
    },
    {
      title: "Team or Global Scoped",
      description: "Team tasks are restricted to team members; Global tasks apply organization-wide.",
    },
    {
      title: "Workflow Tracking",
      description: "Status progression and submissions will be tracked in real-time.",
    },
  ],
  actions: {
    submit: "Create Task",
    submitting: "Creating Task...",
    cancel: "Cancel",
  },
  validation: {
    titleRequired: "Task title is required.",
    teamRequired: "Choose a Team before creating the Task.",
  },
} as const;

