export const TASK_DETAILS_STRINGS = {
  breadcrumbs: {
    dashboard: "Dashboard",
    tasks: "Tasks",
  },
  navigation: {
    backToTasks: "Back to Tasks",
  },
  eyebrow: "Task Details",
  referenceCode: {
    label: "REF",
    copyAria: "Copy reference code",
    copyTitle: "Copy reference code",
    copied: "Copied!",
  },
  badges: {
    overdue: "Overdue",
    onTrack: "On Track",
  },
  actions: {
    assignTask: "Assign Task",
    startTask: "Start Task",
  },
  stepper: {
    title: "Workflow Progress",
    stages: {
      pending: "Created",
      assigned: "Assigned",
      inProgress: "In Progress",
      underReview: "Review",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    subtitles: {
      pending: "Awaiting assignment",
      assigned: "Assigned to member",
      inProgress: "Work underway",
      underReview: "Submission review",
      completed: "Verified & closed",
      cancelled: "Task cancelled",
      revisionRequired: "Revision requested",
    },
  },
  sections: {
    overview: "Task Overview",
    description: "Description",
    remarks: "Instructions & Remarks",
    lifecycle: "Lifecycle & Timeline",
    ownership: "Ownership & Context",
    workspace: "Workspace",
  },
  tabs: {
    submissions: "Submissions",
    attachments: "Attachments",
    history: "Activity History",
  },
  metadata: {
    status: "Status",
    priority: "Priority",
    overdue: "Overdue",
    team: "Team Reference",
    category: "Category Reference",
    createdBy: "Created By",
    dueDate: "Due Date",
    startedAt: "Started",
    completedAt: "Completed",
    cancelledAt: "Cancelled",
    createdAt: "Created",
    updatedAt: "Updated",
    notApplicable: "—",
    none: "None",
    noDescription: "No description provided for this task.",
    noRemarks: "No special remarks or instructions provided.",
  },
  loading: "Loading Task...",
} as const;

export const TASK_TABLE_STRINGS = {
  columns: {
    reference: "Reference",
    title: "Title",
    priority: "Priority",
    status: "Status",
    team: "Team Reference",
    due: "Due",
    overdue: "Overdue",
    created: "Created",
    actions: "Actions",
  },
  labels: {
    teamPrefix: "Team:",
    duePrefix: "Due:",
    createdPrefix: "Created:",
  },
  badges: {
    overdue: "Overdue",
    notOverdue: "No",
  },
  actions: {
    view: "View",
    assign: "Assign",
    start: "Start",
  },
} as const;

export const TASK_CREATE_STRINGS = {
  eyebrow: "Operations",
  title: "Create Task",
  description: "Define a new operational task, assign it to a team, and schedule execution.",
  breadcrumbs: {
    dashboard: "Dashboard",
    tasks: "Tasks",
    current: "New Task",
  },
  navigation: {
    backToTasks: "Back to Tasks",
  },
  sections: {
    generalInfo: "Task Information",
    generalInfoSubtitle: "Define the core requirements, instructions, and internal remarks.",
    configuration: "Assignment & Schedule",
    configurationSubtitle: "Select the responsible team and specify task deadline.",
    guidelines: "Task Lifecycle & Governance",
  },
  fields: {
    titleLabel: "Task Title",
    titleRequired: "*",
    titlePlaceholder: "e.g., Prepare quarterly compliance report",
    titleHelper: "A concise, descriptive summary of the required work.",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Detailed task instructions, deliverables, and acceptance criteria...",
    descriptionHelper: "Provide comprehensive background and execution context.",
    remarksLabel: "Internal Remarks",
    remarksPlaceholder: "Optional internal notes or coordination guidelines...",
    remarksHelper: "Visible to team leads and designated assignees.",
    priorityLabel: "Priority Level",
    priorityHelper: "Select operational urgency level for this task.",
    dueAtLabel: "Due Date & Time",
    dueAtHelper: "Target completion timestamp (optional).",
    dueAtPlaceholder: "Select deadline date & time...",
    dueAtAriaLabel: "Select due date and time",
    teamLabel: "Target Team",
    teamRequired: "*",
    teamHelper: "Choose which team will be responsible for executing this task.",
    selectedTeamPrefix: "Selected:",
    clearTeam: "Clear",
  },
  dateTimePicker: {
    dialogAriaLabel: "Due date and time picker",
    presetsTitle: "Quick Schedule",
    presets: {
      todayEod: "Today 5 PM",
      tomorrowMorning: "Tomorrow 9 AM",
      tomorrowEod: "Tomorrow 5 PM",
      nextWeek: "Next Week",
    },
    timeTitle: "Time",
    hoursLabel: "Hour",
    minutesLabel: "Minute",
    periodLabel: "Period",
    quickTimes: {
      morning: "9:00 AM",
      noon: "12:00 PM",
      eod: "5:00 PM",
      night: "11:59 PM",
    },
    actions: {
      clear: "Clear",
      now: "Now",
      apply: "Apply",
      today: "Today",
      prevMonth: "Previous month",
      nextMonth: "Next month",
    },
  },
  priorities: {
    LOW: { label: "Low", description: "Standard backlog item" },
    MEDIUM: { label: "Medium", description: "Normal operational priority" },
    HIGH: { label: "High", description: "Time-sensitive deliverable" },
    URGENT: { label: "Urgent", description: "Critical blocker requiring immediate action" },
  },
  guidelines: [
    {
      title: "Pending by default",
      description: "Tasks are created in PENDING status until an admin assigns them.",
    },
    {
      title: "Team Scoped",
      description: "Assignment will be restricted to members of the selected team.",
    },
    {
      title: "Workflow Tracking",
      description: "Status progression and submissions will be tracked in real-time.",
    },
  ],
  actions: {
    submit: "Create Task",
    submitting: "Creating Task...",
    cancel: "Cancel",
  },
  validation: {
    titleRequired: "Task title is required.",
    teamRequired: "Choose a Team before creating the Task.",
  },
} as const;
